"""add missing deal columns

Revision ID: 70cadc44bcfa
Revises: 7d2b3da5de12
Create Date: 2026-03-15 04:42:02.025332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cadc44bcfa'
down_revision = '7d2b3da5de12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('underwriting_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('equity_multiple', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('climate_risk', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dscr_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('regulations_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('regulations_json')
        batch_op.drop_column('dscr_json')
        batch_op.drop_column('climate_risk')
        batch_op.drop_column('equity_multiple')
        batch_op.drop_column('underwriting_json')

    # ### end Alembic commands ###
