"""add sourcing and op performance tables

Revision ID: d8d48ec2e8fc
Revises: 70cadc44bcfa
Create Date: 2026-03-15 09:03:58.655718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd8d48ec2e8fc'
down_revision = '70cadc44bcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.alter_column('climate_risk',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.alter_column('climate_data_sources',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.alter_column('climate_data_sources',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.alter_column('climate_risk',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
